GET http://localhost:3000/api HTTP/1.1
###
GET https://localhost:3000/api/fruits HTTP/1.1
###
GET https://localhost:3000/api HTTP/1.1
###
DELETE https://localhost:3000/api/fruits/64db7a92575d359f9e9efc0f HTTP/1.1
###
POST https://localhost:3000/api/users/login HTTP/1.1
content-type: application/json

{
    "username":"test3",
    "password":"youwillneverguessthis"
}
###
POST https://localhost:3000/api/fruits HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwidXNlcklkIjoiNjRmNzE2YjJiMDgyYWYzNzlkMzViZDMwIiwiaWF0IjoxNjkzOTE1MzYwLCJleHAiOjE2OTM5MTg5NjB9.XHxEk6ftyyxJquRCoYY0UJhQpWozeosjMvCK295L46w

{
    "id": "7",
    "name": "Apple"
}
###
POST https://localhost:3000/api/users/signup HTTP/1.1
content-type: application/json

{
    "username": "test3",
    "password": "youwillneverguessthis"
}
###
